language: c++
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libsdl-image1.2-dev
      - libsdl-gfx1.2-dev
      - libsdl-ttf2.0-dev
      - zlib1g-dev
  
script: make -f Makefile.pc
